<?php
$options = $block->getAllRalColor();

// $datacollection=$model->getCollection();
?>
<span class="select_span">Select Color: </span>
<select id="ral_color_drop_down_options" class="ral_color_drop_down_options">
  <?php foreach ($options as $option) : ?>
    <option value="<?php /* @escapeNotVerified */ echo $option['value'] ?>" style="background-color:<?php /* @escapeNotVerified */ echo $option['label'] ?>">
      <?php /* @escapeNotVerified */ echo $option['label'] ?>
    </option>
  <?php endforeach; ?>
</select>

<script>
  require(['jquery'],
    function($) {
      $(document).ready(function() {
 
        document.getElementById("product_addtocart_form").append('<input type="hidden" name="ral_color_id" value="" />');;
        $('select[id=ral_color_drop_down_options]').change(function() {
          $("input[name='ral_color_id']").val($(this).val());
        });
      });
    })
</script>